local MAX_CARD_ID = 20
local textures = {}

function init(self)
    self.card_id = 1
    msg.post('.', 'acquire_input_focus')
    msg.post('.', 'update_ui')
end

function final(self)
    msg.post('.', 'release_input_focus')
end

local function hit_test(self, action, node_name)
    local node = gui.get_node(node_name)
    return gui.pick_node(node, action.x, action.y)
end

local function on_click_left_btn(self)
    self.card_id = self.card_id - 1
    if self.card_id <= 0 then
        self.card_id = MAX_CARD_ID
    end

    msg.post('.', 'update_ui')
end

local function set_texture(node_name, path)
    local data = sys.load_resource(path)
    local img = image.load(data)
    if not img then
        print('can not load image from ' .. path)
        return
    end

    local tex_id = textures[path]
    if tex_id then
        gui.set_texture(gui.get_node(node_name), tex_id)
    else
        tex_id = path
        if gui.new_texture(tex_id, img.width, img.height, img.type, img.buffer) then
            gui.set_texture(gui.get_node(node_name), tex_id)
            textures[path] = tex_id
        else
            print('unable to create texture')
        end
    end
end

local function on_click_right_btn(self)
    self.card_id = self.card_id + 1
    if self.card_id > MAX_CARD_ID then
        self.card_id = 1
    end

    msg.post('.', 'update_ui')
end

local function on_update_ui(self)
    gui.set_text(gui.get_node('lbl_card_id'), ('Card %d'):format(self.card_id))
    set_texture('box_card', ('/res/cards/card_%04d.png'):format(self.card_id))
end

function on_message(self, message_id, message, sender)
    if message_id == hash('update_ui') then
        on_update_ui(self)
    end
end

function on_input(self, action_id, action)
    if action_id == hash('touch') and action.released then
        if hit_test(self, action, 'btn_left') then
            on_click_left_btn(self)
        elseif hit_test(self, action, 'btn_right') then
            on_click_right_btn(self)
        end
    elseif action_id == hash('exit') then
        msg.post('@system:', 'exit', {code = 0})
    end
end
