local tex_manager = require 'test.texture_manager'

local MAX_CARD_ID = 20
local TOUCH = hash('touch')
local EXIT = hash('exit')
local UPDATE_UI = hash('update_ui')

function init(self)
    self.card_id = 1
    msg.post('.', 'acquire_input_focus')
    msg.post('.', 'update_ui')
end

function final(self)
    msg.post('.', 'release_input_focus')
end

function on_message(self, message_id, message, sender)
    if message_id == UPDATE_UI then
        gui.set_text(gui.get_node('lbl_card_id'), ('Card %d'):format(self.card_id))

        local node = gui.get_node('box_card')
        local texture = tex_manager.load(('/res/cards/card_%04d.png'):format(self.card_id))
        gui.set_texture(node, texture)
    end
end

local function hit_test(self, action, node_name)
    local node = gui.get_node(node_name)
    return gui.pick_node(node, action.x, action.y)
end

function on_input(self, action_id, action)
    if action_id == TOUCH and action.released then
        if hit_test(self, action, 'btn_left') then
            self.card_id = self.card_id - 1
            if self.card_id <= 0 then
                self.card_id = MAX_CARD_ID
            end
            msg.post('.', 'update_ui')
        elseif hit_test(self, action, 'btn_right') then
            self.card_id = self.card_id + 1
            if self.card_id > MAX_CARD_ID then
                self.card_id = 1
            end
            msg.post('.', 'update_ui')
        end
    elseif action_id == EXIT then
        msg.post('@system:', 'exit', {code = 0})
    end
end
